name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          token: ${{ secrets._GITHUB_TOKEN }}

    - name: Git pull
      run: git pull --prune

    - name: Calculate release tag
      id: calculate_tag
      run: |
        current_tag=$(git describe --tags --abbrev=0 2>/dev/null || true)
        if [[ -z "$current_tag" ]]; then
          echo "prod$(date +'%Y%m%d').0" >> tag.txt
        else
          # Extract the version number and increment it
          version=$(echo "$current_tag" | grep -oE '[0-9]+')
          next_version=$((version + 1))
          echo "prod$(date +'%Y%m%d').$next_version" >> tag.txt
        fi
      shell: bash

    - name: Read release tag
      id: read_tag
      run: echo "::set-output name=tag::$(cat tag.txt)"
      shell: bash

    - name: Create and push release tag
      run: |
        git tag ${{ steps.read_tag.outputs.tag }}
        git push --tags
      if: steps.read_tag.outputs.tag != ''
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ''
        tag_name: ${{ steps.read_tag.outputs.tag }}
        title: Release ${{ steps.read_tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
