name: Trigger Release in Another Repository

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  trigger_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Release
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets._GITHUB_TOKEN }}" \
          -d '{"event_type": "trigger-release-in-b"}' \
          https://api.github.com/repos/durrello/github-cross-repo-reployment-repo-b/dispatches
      env:
        REPO: github-cross-repo-reployment-repo-b # Replace with the name of the other repository's owner and name
